name: Check links

on:
  schedule:
    - cron: "0 0/12 * * *"
  workflow_dispatch:
  push:
  pull_request:

jobs:
  check-link:

    runs-on: ubuntu-latest

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
